source 'https://rubygems.org'
gem 'rails', '4.2.0'

group :production do
  gem 'puma'
end

group :develoment do
  gem 'sqlite3'
  gem 'quiet_assets'
  gem 'letter_opener'
  gem 'thin'
  gem 'spring'
  gem 'byebug'
end

# General
gem 'jquery-rails'
gem 'sorcery'
gem 'coffee-rails'
gem 'therubyracer'
gem 'turbolinks'